### ISSUE TITLE
Ch 5: Understanding the variability of a point estimate and unbiasedness

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#10]
In this section we simulate samples of size n = 1000 from a population of N = 250million with the assumed proportion parameter of 0.887. And then we're say that the generated sampling distribution is centered at 0.887, and hence the estimate of p-hat = 0.887 is unbiased. 

But the sampling distribution was generated assuming the true p is 0.887, so we shouldn't use the resulting sampling distribution to justify unbiasedness.

Am I missing something?

**Comment by DavidDiez** [comment]
I've reframed the section to use p = 0.88 instead and suppose this is the truth. This is captured in the following commit:
https://github.com/OpenIntroOrg/openintro-statistics/commit/c800e0cc95efc07b345d25be4170752e24d4cba2
