### ISSUE TITLE
Ch 5: Definition of standard error

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#11]
https://github.com/OpenIntroOrg/openintro-statistics/blob/b7e661929a25ca0f7fb530139e1c5aa015f1f459/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L212-L218

A more accurate definition would be that the variability of the sample statistic is called the standard error when calculated using sample statistics, since it's called the standard deviation if calculated using true population parameters.

Not sure if going into that distinction is worthwhile here, since the latter case rarely happens, but the definition here makes it sound like the variability of a sample statistic is always called standard error, which is not accurate.

Relatedly, the formula below is not correct:

https://github.com/OpenIntroOrg/openintro-statistics/blob/b7e661929a25ca0f7fb530139e1c5aa015f1f459/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L284

If using p, this should be called sigma. If using p-hat, it would be called SE.

I would suggest the following changes to address these two concerns:

- In line 214: `We typically measure the variability of a sampling distribution, or the variability of a point estimate, with \termsub{standard error}{standard error (SE)}, and the notation $SE_{\hat{p}}$ is used for the standard error associated with the sample proportion.`
- In line 284: `sigma_{\hat{p}} &= \sqrt{\frac{p (1 - p)}{n}}`
- And then a new line 286 before discussing the S-F condition: `Often we don't know p, so we can't directly calculate sigma_{\hat{p}}, and instead estimate it with SE_{\hat{p}} &= \sqrt{\frac{\hat{p} (1 - \hat{p})}{n}}.`

**Comment by mine-cetinkaya-rundel** [comment]
If this change is implemented it will also affect the following line,

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L952-L954

where we could do away with the approximation since by definition SE is an approximation, and say

 SE = \sqrt{\frac{\wsjebolapollprop{} (1 - \wsjebolapollprop{})}{\wsjebolapollsize{}}}

**Comment by DavidDiez** [comment]
Let's catch up on this in our next meeting; I've added a note there so this doesn't get lost.
