### ISSUE TITLE
Ch 5: How to verify sample observations are independent box

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#12]
This tip box states

https://github.com/OpenIntroOrg/openintro-statistics/blob/b7e661929a25ca0f7fb530139e1c5aa015f1f459/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L339-L340

Do we want to give a justification for this? It seems like a stretch to expect students can justify *why* this is the case. However I'm not sure how feasible it is to do that succinctly.

**Comment by OpenIntroOrg** [comment]
I'm not too concerned about this one... I worry saying too much more will make it into a tangent and then more distracting. I've slightly tweaked to the following:

"""
  Even if the sample is bigger than 10\%, assuming independence
  will lead to more conservative results than what we would
  get using more advanced methods.
"""
