### ISSUE TITLE
Ch 5: Figure 5.5 - Sampling dists for several p and n

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#13]
- Can we add a y-axis label to the first plot in each row to indicate the value of p so a reader who doesn't read the caption (✋) can quickly understand what the differences between the rows are. I'm indifferent to additionally including the text in the caption, no objections to leaving it there.
- Is the blue color not used here, or not visible due to bins being very narrow? If former, might be nice to add for consistency.

**Comment by OpenIntroOrg** [comment]
For the row labels, this is designed this way for a couple reasons:
- It will look clear in the print book: the preceding figure plus this figure will read across two pages (no page turn), so the row labels will be clear from the previous figure.
- Adding label into the second plot will compress the 3 columns of plots, degrading the experience in both the print and PDF experiences (vs just leaving it as it is and slightly degrading the PDF experience).

I've adjusted the border of the boxes to be blue, so now it will look more elegant. :)
