### ISSUE TITLE
Ch 5: Use of "often" in probability calculation

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#15]
For some reason the word "often" bugged me here, how about instead of

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L803-L804

we say

```
If X is a normally distributed random variable, what is the probability of the value of X to be within 2.58 standard deviations of the mean?
```

**Comment by OpenIntroOrg** [comment]
Sounds good -- now updated.
