### ISSUE TITLE
Ch 5: CIs only try to capture population parameters

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#16]
I really like the essence of the following summary, but the image of CIs actively capturing something is a bit odd to me.

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1088-L1093

I propose the following alternative wording:

```
 Another important consideration of confidence intervals is that they 
 \emph{are only about the population parameter}. A confidence 
 interval says nothing about individual observations, a proportion of the 
 observations, or point estimates. Confidence intervals only provide a 
 plausible range for population parameters, at a given confidence 
 level.
 population parameters. 
```

**Comment by OpenIntroOrg** [comment]
Sounds good -- I've taken your updated version nearly verbatim.
