### ISSUE TITLE
Ch 5: Link to Factfulness doesn't work

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#17]
https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1113

**Comment by mine-cetinkaya-rundel** [comment]
Also, we should list all three authors if we're mentioning any -- the other two are Anna Rosling Rönnlund and Ola Rosling.

**Comment by OpenIntroOrg** [comment]
Sounds good, I've added a \Comment into the book to track this until it is resolved.
