### ISSUE TITLE
Ch 5: Is Rosling sample size really 50?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#18]
This is in reference to 

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1357-L1358

and specifically `\roslingAsize{}`.

I thought the sample size was larger, is this a subsample?

**Comment by OpenIntroOrg** [comment]
It is larger -- I took a subsample for illustrative purposes.
