### ISSUE TITLE
Ch 5: Indentation at the beginning of GP 5.22 and 5.23

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#19]
See image below:

<img width="91" alt="screen shot 2018-12-02 at 4 13 31 pm" src="https://user-images.githubusercontent.com/5965649/49345059-a838a780-f64d-11e8-9b39-5b6aaf4cd23a.png">

Not sure why the indentation is happening.

This is in reference to 

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1456

and 

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1503

**Comment by OpenIntroOrg** [comment]
This is an oddity of the new environments created for the new styles. When a \label{} is added at the start of an example or guided practice, this extra space gets inserted. The solution is to put a `%` after the \label{}. I'll fix these elsewhere in the text during final formatting, though I've fixed these two instances now so they are done. :)
