### ISSUE TITLE
Ch 5: Too many consecutive GPs

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#20]
I suggest turning the following to text

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1629-L1642

and then keeping the next one as a GP.

This way it's not too many consecutive GPs on a page (I find that a bit distracting) and also gives some intuition about errors before asking a question.

**Comment by OpenIntroOrg** [comment]
Sounds good, now changed to an example.
