### ISSUE TITLE
Ch 5: a "tool" called p-value

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#21]
I'm not a fan of the word "tool" here

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1701

though I can't think of a term that is necessarily better either: `measure`, `statistic`, `probability`?

**Comment by OpenIntroOrg** [comment]
I agree it sounds weird -- I've switched to the `statistic` option you suggested, which I think sounds better. If you think of another option you like more, I'm open to other options.
