### ISSUE TITLE
Ch 5: Avoid xx.0

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#22]
Can we show this as 37% as opposed to 37.0% throughout, and similarly 0.37 instead of 0.370?

https://github.com/OpenIntroOrg/openintro-statistics/blob/ecad440aa2922a5dd8a4fd7eaa9cf577e26fd119/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1757

**Comment by OpenIntroOrg** [comment]
Sure, now updated.
