### ISSUE TITLE
OS 4: Is data plural or singular?

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#23]
Currently we use it both as singular and plural, and I'm actually fine with this. But wanted to confirm this was intentional.

e.g.

- "data suggests the actual support is close to"
- "data provide strong evidence"

**Comment by OpenIntroOrg** [comment]
I always intend plural for consistency -- thanks for catching the "data suggests"! If you spot others, we should fix them.
