### ISSUE TITLE
Ch 5: "Applying" the normal model

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#24]
Throughout the chapter there is phrasing like `"the normal model may be applied to p-hat"`. I prefer phrasing this as `"p-hat can be assumed to follow a normal distribution"`. We're not really "applying" something, we're assuming CLT holds and basing calculations off of that. What do you think about replacing this language with my suggested phrasing?

**Comment by OpenIntroOrg** [comment]
I've modified the phrasing throughout, usually writing something like "$\hat{p}$ may be modeled using a normal distribution". I've also tweaked this in Chapter 6.
