### ISSUE TITLE
Ch 5: Section 5.3.2 Testing hypotheses using confidence intervals

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#25]
This section tests HTs on p using CIs, but the standard deviation/error used are different when doing a CI vs. HT.

Unless I missed something in my review, this is not mentioned explicitly.

**Comment by OpenIntroOrg** [comment]
Nope, it's not mentioned. Since you raised it, I've added a footnote to clarify since I suspect it will otherwise get raised by others. The footnote may not be a satisfactory solution to some... we'll see if anyone is meaningfully concerned with that bandaid in place.
