### ISSUE TITLE
Ch 5: Ex 5.28 Wording and symbol mismatch in alternative hypothesis

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#26]
Wording below says majority but the alternative is defined as two-sided.

https://github.com/OpenIntroOrg/openintro-statistics/blob/b7e661929a25ca0f7fb530139e1c5aa015f1f459/ch_foundations_for_inf/TeX/ch_foundations_for_inf.tex#L1737-L1747

I know we want to avoid one sided tests, how about changing the wording for the question?

**Comment by OpenIntroOrg** [comment]
It's intended to be one-sided, but it sounds like the language isn't clear. I've adjusted it from
"majority support (or oppose) to expanding the use of coal."
to
"majority support or oppose (though we do not known which one!) expanding the use of coal."

Let me know if that doesn't clarify it enough (suggestions welcome).
