### ISSUE TITLE
Guided practice answer hyperlinks

### ISSUE THREAD

**Issue by jsta** [OpenIntroOrg/openintro-statistics#3]
I really like the hyperlinks from the guided practice prompts to the answers. Also it makes sense that the hyperlinks at the actual answers point to web resources. However, when I download the pdf these answer hyperlinks (to external resources) do not launch my browser. Instead, they open a text file like this:

> 
	<html>
	<head>
	<title>Redirecting...</title>
	<meta http-equiv="refresh" content="0; url=http://www.fda.gov/food/foodborneillnesscontaminants/metals/ucm115644.htm">
	
>
	<script type="text/javascript">
	  window.location.href = "http://www.fda.gov/food/foodborneillnesscontaminants/metals/ucm115644.htm"
	</script></head>
	<body>
	<p>
	  If you are not redirected automatically, use the following link:<br>
	  <a href="http://www.fda.gov/food/foodborneillnesscontaminants/metals/ucm115644.htm">http://www.fda.gov/food/foodborneillnesscontaminants/metals/ucm115644.htm</a>
	</p>
	</body>
	</html>

I am using the Okular pdf viewer.

**Comment by beanumber** [comment]
@jsta do you notice the same behavior if you open it in Evince or another PDF viewer (e.g. Preview, Adobe Reader)?

**Comment by jsta** [comment]
Sorry about this, it works in Evince. I needed to set a kde browser default (http://askubuntu.com/questions/160918/clicking-links-in-pdfs-opened-with-okular-opens-abiword-instead-of-the-default).
