### ISSUE TITLE
Compiling give errors

### ISSUE THREAD

**Issue by hmarlo** [OpenIntroOrg/openintro-statistics#4]
Compilation gives a bunch of errors about "file not found". I think that you changed some of the folder's names, but not corrected it in the main document. Maybe I could help to correct it.

**Comment by OpenIntroOrg** [comment]
The files compile successfully for me. Can you be more specific about the errors you're seeing?

**Comment by hmarlo** [comment]
Sincerely, I don't remember. I will try to reproduce the issue these days :)

**Comment by hmarlo** [comment]
After installing texlive-full, the error that I'm seeing is `! LaTeX Error: File `extraTeX/icons/video_camera' not found.`. Which package do you use for icons?

Thanks!

**Comment by OpenIntroOrg** [comment]
I suspect that it requires the explicit image / file extension label (TeXShop doesn't require this, which is what our team has been using); the most recent commit includes ".png" on the end of the file name: extraTeX/icons/video_camera.png.

Re-open or create a new issue if it is still not resolved!
