### ISSUE TITLE
Issues compiling the print color book

### ISSUE THREAD

**Issue by eric-kruger** [OpenIntroOrg/openintro-statistics#6]
Hi what are the changes that need to be made to main.tex to print the color print book, since the default is the tablet version of the book?  I tried reverse some of the comments but could not get the document to compile.

**Comment by OpenIntroOrg** [comment]
Check out the main.tex file and do some combination of including and commenting out lines 14, 17, and 24 to get the desired format of B&W-print, Color-print, and tablet variants. In short, exactly one of lines 14 or 17 should be included, and line 24 is optional.
