### ISSUE TITLE
Ch 5: "accuracy" of parameter estimates

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [OpenIntroOrg/openintro-statistics#7]
I'm not sure if accuracy is the right word here, as opposed to precision, or both.

In discussing confidence intervals we talk about accuracy with regards to confidence levels, and precision with regards to magnitude of the margin of error. I think we mean both here so how about instead of 

https://github.com/OpenIntroOrg/openintro-statistics/blob/b7e661929a25ca0f7fb530139e1c5aa015f1f459/ch_foundations_for_inf/TeX/ch_inference_for_props.tex#L6

we say

`accuracy and precision of parameter estimates`?

**Comment by OpenIntroOrg** [comment]
These spots have now been revised to be more careful on this wording.
